/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;
import java.util.*;


public class Huffman {

public static Map<Character, Integer> map;
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Huffman().getGreeting());
        map = new HashMap<>();
        PriorityQueue<Character> tree = new PriorityQueue();
    }

    public static void countFrequencies(String input){
        for(int i = 0; input.length() > i; i++){
            map.put(input.charAt(i), (map.get(input.charAt(i) + 1)));
        }
    }
}
