/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;
import java.util.*;


public class Huffman {

public static Map<Character, Integer> map;
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Huffman().getGreeting());
        map = new HashMap<>();
        PriorityQueue<Character> tree = new PriorityQueue();
    }

    public static void countFrequencies(String input){
        for(int i = 0; input.length() > i; i++){
            map.put(input.charAt(i), (map.get(input.charAt(i) + 1)));
        }
    }

    public class Node{
        //Fields for node.
        int frequency;
        Character character;
        Node left;
        Node right;

        //Constructor for leaf nodes
        Node(int frequency, Character character){
            this.left = null; //leaf node, so set node's children to null.
            this.right = null;
            this.frequency = frequency;
            this.character = character;
        }

        //Constructor for internal nodes
        Node(int frequency, Node left, Node right){
            this.left = left;
            this.right = right;
            this.frequency = frequency;
            this.character = null; //Internal node, so set node's character field to null.
        }

    }
}
